# Site settings
title: Bigdata Resource
SEOTitle: Bigdata Resource | Bigdata Resource
header-img: img/home-bg.jpg
email: deqiangqin@gmail.com
copyright_name: Bigdata Resource
description: "About bigdata resource,such as news,blogs,datas,codes,public project.Most of posts is my experience."
baseurl: ""
#url: "http://bigdataresource.site"

#twitter_username: SBootstrap
email_username: deqiangqin@gmail.com
github_username:  qindeqiang
#facebook_username:  StartBootstrap
#weibo_username: qindeqiang
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-110178637-1

# Build settings
markdown: kramdown
kramdown:
  input:  GFM
  use_coderay: true
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Sidebar settings
sidebar: true
sidebar-about-description: "Hello,EveryOne"
sidebar-avatar: /img/7.jpg

intensedebate_comments: true
